[tool.isort]
src_paths = ["apps/worri_api"]
line_length = 79
force_single_line = true

[tool.black]
line-length = 79
preview = true

[tool.pyright]
typeCheckingMode = "strict"
reportMissingTypeStubs = false
reportUnknownMemberType = false
reportUnknownVariableType = false
include = ["apps/worri_api"]
exclude = ["**/venv"]
