/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/users/{username}/": {
    get: operations["users_retrieve"];
  };
  "/api/users/create/": {
    post: operations["users_create_create"];
  };
  "/api/users/current/": {
    get: operations["users_current_retrieve"];
  };
  "/api/users/login/": {
    post: operations["users_login_create"];
  };
  "/api/users/logout/": {
    post: operations["users_logout_create"];
  };
  "/api/users/register/": {
    post: operations["users_register_create"];
  };
  "/api/users/setup/": {
    get: operations["users_setup_retrieve"];
  };
  "/api/users/update/": {
    patch: operations["users_update_partial_update"];
  };
  "/api/users/workspaces/": {
    get: operations["users_workspaces_retrieve"];
  };
  "/api/websites/{id}/": {
    get: operations["websites_retrieve"];
    patch: operations["websites_partial_update"];
  };
  "/api/websites/create/": {
    post: operations["websites_create_create"];
  };
  "/api/workspaces/{name}/": {
    get: operations["workspaces_retrieve"];
    delete: operations["workspaces_destroy"];
    patch: operations["workspaces_partial_update"];
  };
  "/api/workspaces/{name}/members/": {
    get: operations["workspaces_members_retrieve"];
  };
  "/api/workspaces/{name}/websites/": {
    get: operations["workspaces_websites_retrieve"];
  };
  "/api/workspaces/create/": {
    post: operations["workspaces_create_create"];
  };
  "/api/workspaces/join/": {
    post: operations["workspaces_join_create"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    CreateWorkspaceErrorOut: {
      name: string[];
    };
    CreateWorkspaceInRequest: {
      name: string;
    };
    GenericOut: {
      detail: string;
    };
    JoinWorkspaceInRequest: {
      access_code: string;
    };
    NeedSetupOut: {
      need_setup: boolean;
    };
    PatchedUpdateWorkspaceMemberInRequest: {
      password?: string;
      role?: components["schemas"]["RoleEnum"];
    };
    PatchedWebsiteOutRequest: {
      name?: string;
      domain?: string;
      created_by?: string;
    };
    PatchedWorkspaceOutRequest: {
      name?: string;
      access_code?: string;
    };
    RegisterErrorOut: {
      detail: string;
      username: string[];
      email: string[];
      password: string[];
    };
    /**
     * @description * `ADMIN` - ADMIN
     * * `EDITOR` - EDITOR
     * * `VIEWER` - VIEWER
     * @enum {string}
     */
    RoleEnum: "ADMIN" | "EDITOR" | "VIEWER";
    UserInRequest: {
      username: string;
      role: components["schemas"]["RoleEnum"];
      password: string;
      workspace: string;
    };
    UserLoginInRequest: {
      username: string;
      password: string;
    };
    UserOut: {
      id: number;
      first_name?: string;
      last_name?: string;
      username: string;
      /**
       * Email address
       * Format: email
       */
      email?: string;
      role: components["schemas"]["RoleEnum"];
      workspace: readonly string[];
    };
    UserRegisterInRequest: {
      username: string;
      /**
       * Email address
       * Format: email
       */
      email?: string;
      password: string;
    };
    WebsiteInRequest: {
      workspace: string;
      name: string;
      domain: string;
    };
    WebsiteOut: {
      id: number;
      name: string;
      domain: string;
      created_by: string;
    };
    WebsitesListOut: {
      websites: components["schemas"]["WebsiteOut"][];
    };
    WorkspaceListOut: {
      workspaces: components["schemas"]["WorkspacesOut"][];
    };
    WorkspaceMemberOut: {
      id: number;
      username: string;
      role: components["schemas"]["RoleEnum"];
      /** Format: date-time */
      date_joined?: string;
    };
    WorkspaceMembersListOut: {
      members: components["schemas"]["WorkspaceMemberOut"][];
    };
    WorkspaceOut: {
      name: string;
      access_code: string;
    };
    WorkspacesOut: {
      name: string;
      access_code: string;
      created_by: string;
      members_count: string;
      websites_count: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  users_retrieve: {
    parameters: {
      path: {
        username: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["WorkspaceMemberOut"];
        };
      };
    };
  };
  users_create_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserInRequest"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["GenericOut"];
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["RegisterErrorOut"];
        };
      };
    };
  };
  users_current_retrieve: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["UserOut"];
        };
      };
    };
  };
  users_login_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserLoginInRequest"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["UserOut"];
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["GenericOut"];
        };
      };
    };
  };
  users_logout_create: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["GenericOut"];
        };
      };
    };
  };
  users_register_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserRegisterInRequest"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["GenericOut"];
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["RegisterErrorOut"];
        };
      };
    };
  };
  users_setup_retrieve: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["NeedSetupOut"];
        };
      };
    };
  };
  users_update_partial_update: {
    parameters: {
      query: {
        username: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedUpdateWorkspaceMemberInRequest"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["GenericOut"];
        };
      };
    };
  };
  users_workspaces_retrieve: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["WorkspaceListOut"];
        };
      };
    };
  };
  websites_retrieve: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this website. */
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["WebsiteOut"];
        };
      };
    };
  };
  websites_partial_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this website. */
        id: number;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedWebsiteOutRequest"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["WebsiteOut"];
        };
      };
    };
  };
  websites_create_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["WebsiteInRequest"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["GenericOut"];
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["GenericOut"];
        };
      };
    };
  };
  workspaces_retrieve: {
    parameters: {
      path: {
        name: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["WorkspaceOut"];
        };
      };
    };
  };
  workspaces_destroy: {
    parameters: {
      path: {
        name: string;
      };
    };
    responses: {
      /** @description No response body */
      204: {
        content: never;
      };
    };
  };
  workspaces_partial_update: {
    parameters: {
      path: {
        name: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedWorkspaceOutRequest"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["WorkspaceOut"];
        };
      };
    };
  };
  workspaces_members_retrieve: {
    parameters: {
      path: {
        name: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["WorkspaceMembersListOut"];
        };
      };
    };
  };
  workspaces_websites_retrieve: {
    parameters: {
      path: {
        name: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["WebsitesListOut"];
        };
      };
    };
  };
  workspaces_create_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateWorkspaceInRequest"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["GenericOut"];
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["CreateWorkspaceErrorOut"];
        };
      };
    };
  };
  workspaces_join_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["JoinWorkspaceInRequest"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["GenericOut"];
        };
      };
    };
  };
}
