# Generated by Django 5.0 on 2024-05-27 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='core.workspace'),
        ),
    ]
