# Generated by Django 5.0 on 2024-05-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default=123, max_length=254, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
